In [24]:
using LinearAlgebra

x=rand(1000)
A=rand(1000,1000)
b=A*x

1000-element Array{Float64,1}:
 234.43807851349695
 234.80149508110892
 235.9712140053221 
 243.7969531498147 
 239.79342233216502
 238.44359380042474
 238.5016371566039 
 232.8906504233929 
 235.74756405515822
 237.52789835300447
 237.00133064938473
 232.4362310066665 
 229.2992944883824 
   ⋮               
 238.83446281910028
 234.0276684884246 
 234.9289776221397 
 245.45758729081942
 240.11246325089897
 232.16749096583902
 230.1103687691216 
 232.5448032486356 
 241.8143376760524 
 231.97699451266416
 235.1153399977224 
 238.88611298140657

In [25]:
@time inv(A)*b


  0.567209 seconds (948.89 k allocations: 54.190 MiB, 15.34% gc time)


1000-element Array{Float64,1}:
 0.16523754150608738
 0.42209356323959213
 0.33284426718817883
 0.7839691608480468 
 0.4675304794329662 
 0.9568251761420505 
 0.28320200724871114
 0.47062097287394167
 0.7653665851609333 
 0.13408009626903095
 0.7798311929733259 
 0.5732453212322852 
 0.5367669433543334 
 ⋮                  
 0.0692890298689477 
 0.2648797499756057 
 0.24714527668841413
 0.6564877117997128 
 0.21042889429124756
 0.39432431382284605
 0.21371141404854832
 0.16087380221267011
 0.09964164977235868
 0.7615062125647682 
 0.06778031110903271
 0.7311320621312216 

In [26]:
@time A\b

  1.460729 seconds (2.75 M allocations: 138.094 MiB, 8.60% gc time)


1000-element Array{Float64,1}:
 0.16523754150700667
 0.42209356323619796
 0.3328442671907725 
 0.7839691608471551 
 0.46753047943258375
 0.9568251761409394 
 0.2832020072487361 
 0.4706209728748451 
 0.7653665851627813 
 0.13408009626988093
 0.7798311929728874 
 0.5732453212327198 
 0.5367669433558059 
 ⋮                  
 0.06928902986934495
 0.26487974997254893
 0.24714527668859512
 0.6564877117997661 
 0.21042889428953807
 0.3943243138214317 
 0.21371141405020616
 0.16087380221390543
 0.09964164977202565
 0.7615062125645495 
 0.06778031110871846
 0.7311320621314532 

In [27]:
Af=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
1000×1000 Array{Float64,2}:
 1.0          0.0          0.0          …   0.0        0.0       0.0
 0.00980081   1.0          0.0              0.0        0.0       0.0
 0.0237377    0.00902936   1.0              0.0        0.0       0.0
 0.936465    -0.775361    -0.407133         0.0        0.0       0.0
 0.331287    -0.311726     0.445324         0.0        0.0       0.0
 0.452777     0.539117    -0.263531     …   0.0        0.0       0.0
 0.982588    -0.867559     0.401531         0.0        0.0       0.0
 0.248815     0.584404     0.000544304      0.0        0.0       0.0
 0.0444214    0.0852703    0.943808         0.0        0.0       0.0
 0.924597    -0.29915     -0.581601         0.0        0.0       0.0
 0.66615     -0.615927    -0.0498667    …   0.0        0.0       0.0
 0.138713     0.0899056   -0.0969944        0.0        0.0       0.0
 0.630392    -0.436881     0.73169          0.0        0.0       0.0
 ⋮                                  

In [28]:
function ul_solve(A, b)
    Af=factorize(A)
    return Af\b
end

@time ul_solve(A, b)

  0.034537 seconds (915 allocations: 7.701 MiB)


1000-element Array{Float64,1}:
 0.16523754150700667
 0.42209356323619796
 0.3328442671907725 
 0.7839691608471551 
 0.46753047943258375
 0.9568251761409394 
 0.2832020072487361 
 0.4706209728748451 
 0.7653665851627813 
 0.13408009626988093
 0.7798311929728874 
 0.5732453212327198 
 0.5367669433558059 
 ⋮                  
 0.06928902986934495
 0.26487974997254893
 0.24714527668859512
 0.6564877117997661 
 0.21042889428953807
 0.3943243138214317 
 0.21371141405020616
 0.16087380221390543
 0.09964164977202565
 0.7615062125645495 
 0.06778031110871846
 0.7311320621314532 

In [29]:
v1 = @time inv(A)*b
v2 = @time A\b
v3 = @time factorize(A)\b

  0.155000 seconds (11 allocations: 8.134 MiB)
  0.239386 seconds (9 allocations: 7.645 MiB, 91.41% gc time)
  0.059356 seconds (9 allocations: 7.645 MiB)


1000-element Array{Float64,1}:
 0.16523754150700667
 0.42209356323619796
 0.3328442671907725 
 0.7839691608471551 
 0.46753047943258375
 0.9568251761409394 
 0.2832020072487361 
 0.4706209728748451 
 0.7653665851627813 
 0.13408009626988093
 0.7798311929728874 
 0.5732453212327198 
 0.5367669433558059 
 ⋮                  
 0.06928902986934495
 0.26487974997254893
 0.24714527668859512
 0.6564877117997661 
 0.21042889428953807
 0.3943243138214317 
 0.21371141405020616
 0.16087380221390543
 0.09964164977202565
 0.7615062125645495 
 0.06778031110871846
 0.7311320621314532 

In [30]:
abs(norm(v1) - norm(x))

1.7408297026122455e-13

In [31]:
abs(norm(v2) - norm(x))

2.4868995751603507e-14

In [32]:
abs(norm(v3) - norm(x))

2.4868995751603507e-14

In [33]:
using CSV
using DataFrames
using Statistics
using Polynomials

input="data_lab3.csv"
data=CSV.read(input, delim=",")

data2 = by(data, :size,  df->DataFrame(
        naive_times_mean=mean(df[:naive_time]), naive_times_std=std(df[:naive_time]),
        better_times_mean=mean(df[:better_time]), better_times_std=std(df[:better_time]), 
        blas_times_mean=mean(df[:blas_time]), blas_times_std=std(df[:blas_time])
        ))

naive_fit_c=polyfit(data2[:size], data2[:naive_times_mean], 3)

println(naive_fit_c)

Poly(0.0030567402386081455 - 7.451374235460676e-5*x + 3.325210510766445e-7*x^2 + 4.490785309334662e-9*x^3)


In [34]:
A = zeros(length(data2[:size]), 4)

15×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [35]:
x=data2[:size]
y=data2[:naive_times_mean]

15-element Array{Float64,1}:
 0.00024014769999999998
 0.0016178338          
 0.0019664978          
 0.004244504           
 0.0080576229          
 0.0137404852          
 0.022097399           
 0.0368226552          
 0.058389222500000004  
 0.0740835239          
 0.0990365339          
 0.1309728529          
 0.16804370890000003   
 0.2157794246          
 0.25534797340000004   

In [36]:
A[:,1]=x.^3
A[:,2]=x.^2
A[:,3]=x
A[:,4]=ones(length(data2[:size]))

15-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [37]:
using LinearAlgebra

AF = factorize(A)
println(reverse(AF.R\((Transpose(AF.Q)*y)[1:4])))
println(reverse(A\y))
println(naive_fit_c)

[0.00305674, -7.45137e-5, 3.32521e-7, 4.49079e-9]
[0.00305674, -7.45137e-5, 3.32521e-7, 4.49079e-9]
Poly(0.0030567402386081455 - 7.451374235460676e-5*x + 3.325210510766445e-7*x^2 + 4.490785309334662e-9*x^3)


In [1]:
using LinearAlgebra
using Statistics

function my_eigen(A)
    n = length(A[:,1])
    
    last_diagonal = zeros(n)
    eigen_vectors = Matrix(I, n, n)
    
    kill_switch = 0
    while kill_switch < 10
        kill_switch += 1
        
        AF=qr(A)
        A=AF.R*AF.Q
        
        eigen_vectors *= AF.Q
        
        max_diff = -1

        for k=1:length(A[:,1])
            max_diff = max(abs(abs(last_diagonal[k]) - abs(A[k, k])), max_diff)
            last_diagonal[k] = A[k ,k]
        end

        if max_diff < 10e-9
            break
        end
    end
    return Dict("values"=>last_diagonal, "vectors"=>eigen_vectors)
end


my_eigen (generic function with 1 method)

In [4]:
using LinearAlgebra
using Statistics

Test = [2 -1 -1 0; -1 3 -1 -1; -1 -1 3 -1; 0 -1 -1 2]
println(Test)

[2 -1 -1 0; -1 3 -1 -1; -1 -1 3 -1; 0 -1 -1 2]


In [5]:
map(x -> round(x * 100)/100, my_eigen(Test)["values"])

4-element Array{Float64,1}:
 4.0
 4.0
 2.0
 0.0

In [6]:
map(x -> round(x * 100)/100, eigvals(Test))

4-element Array{Float64,1}:
 0.0
 2.0
 4.0
 4.0

In [7]:
map(x -> round(x * 100)/100, my_eigen(Test)["vectors"])

4×4 Array{Float64,2}:
  0.5   0.0   -0.71  0.5
 -0.5   0.71   0.0   0.5
 -0.5  -0.71  -0.0   0.5
  0.5  -0.0    0.71  0.5

In [8]:
map(x -> round(x * 100)/100, eigvecs(Test))

4×4 Array{Float64,2}:
 -0.5   0.71   0.5   0.0 
 -0.5  -0.0   -0.5   0.71
 -0.5  -0.0   -0.5  -0.71
 -0.5  -0.71   0.5   0.0 

In [2]:
function matrix_pow(A, a)
    eigen_ = my_eigen(A)
    eigen_values = eigen_["values"]
    eigen_vectors = eigen_["vectors"]
    
    n=length(eigen_values)
    
    diagonal_matrix = zeros(n, n)
    
    for k=1:n
        diagonal_matrix[k ,k]=eigen_values[k]^a
    end
    
    A=eigen_vectors*diagonal_matrix*inv(eigen_vectors)
    
    return A
end

matrix_pow (generic function with 1 method)

In [17]:
map(x->round(x), matrix_pow(Test, 3))

4×4 Array{Float64,2}:
  20.0  -16.0  -16.0   12.0
 -16.0   48.0  -16.0  -16.0
 -16.0  -16.0   48.0  -16.0
  12.0  -16.0  -16.0   20.0

In [18]:
Test^3

4×4 Array{Int64,2}:
  20  -16  -16   12
 -16   48  -16  -16
 -16  -16   48  -16
  12  -16  -16   20